apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-csharp
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XStorageBucket
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-template-csharp
