apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-sdk-csharp-sample
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XStorageBucket
  mode: Pipeline
  pipeline:
  - step: run-the-function
    functionRef:
      name: function-sdk-csharp-sample
