apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-csharp
spec:
  compositeTypeRef:
    apiVersion: azuread.company.com/v1alpha1
    kind: xApplication
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-template-csharp
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Input
      example: "Hello world"
