apiVersion: applications.azuread.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: oidc-guard:applications.azuread.upbound.io/Application:oidc-guard/app-terraform-azure-da-platform-dev-oidc-guard
    crossplane.io/external-create-pending: 2024-07-18T16:04:31Z
    crossplane.io/external-create-succeeded: 2024-07-18T16:04:31Z
    crossplane.io/external-name: /applications/35839148-f20a-482a-beca-3d12e156cdb5
  creationTimestamp: 2024-07-18T16:04:31.0000000Z
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 4
  labels:
    da.app.com/alloy-name: oidc-guard-app-reg
  name: app-terraform-azure-da-platform-dev-test-object-004
  resourceVersion: "8520605"
  uid: 54db7ff4-9d36-4aba-bf9f-33c81ae1aef5
spec:
  deletionPolicy: Delete
  forProvider:
    api:
    - requestedAccessTokenVersion: 1.0
    displayName: app-terraform-azure-da-platform-dev-oidc-guard
    featureTags:
    - {}
    marketingUrl: https://oidc-guard.app.com/
    optionalClaims:
    - {}
    owners:
    - 3983c9fb-06c6-4306-b917-d9b68fe45a50
    - 20852935-49a0-4ec7-93f7-3666aa77a316
    - 575222ec-4a82-4fe2-a894-f3b7242e6841
    publicClient:
    - {}
    requiredResourceAccess:
    - resourceAccess:
      - id: 37f7f235-527c-4136-accd-4a02d197296e
        type: Scope
      - id: 14dad69e-099b-42c9-810b-d002981feec1
        type: Scope
      - id: 64a6cdd6-aab1-4aaf-94b8-3cc8405e90d0
        type: Scope
      resourceAppId: 00000003-0000-0000-c000-000000000000
    signInAudience: AzureADMyOrg
    singlePageApplication:
    - {}
    web:
    - redirectUris:
      - http://localhost:7007/api/auth/microsoft/handler/frame
      - https://oidc-guard.app.com/api/auth/microsoft/handler/frame
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: azure-app-reg-secret
    namespace: oidc-guard
status:
  atProvider:
    api:
    - mappedClaimsEnabled: false
      requestedAccessTokenVersion: 1.0
    applicationId: eaf38126-70c4-4c27-bbc9-5a3df820ef05
    clientId: eaf38126-70c4-4c27-bbc9-5a3df820ef05
    description: ""
    deviceOnlyAuthEnabled: false
    disabledByMicrosoft: <nil>
    displayName: app-terraform-azure-da-platform-dev-oidc-guard
    fallbackPublicClientEnabled: false
    featureTags:
    - customSingleSignOn: false
      enterprise: false
      gallery: false
      hide: false
    id: /applications/35839148-f20a-482a-beca-3d12e156cdb5
    logoImage: ""
    logoUrl: ""
    marketingUrl: https://oidc-guard.app.com/
    notes: ""
    oauth2PostResponseRequired: false
    objectId: 35839148-f20a-482a-beca-3d12e156cdb5
    optionalClaims:
    - {}
    owners:
    - 20852935-49a0-4ec7-93f7-3666aa77a316
    - 3983c9fb-06c6-4306-b917-d9b68fe45a50
    - 575222ec-4a82-4fe2-a894-f3b7242e6841
    preventDuplicateNames: false
    privacyStatementUrl: ""
    publicClient:
    - {}
    publisherDomain: app.com
    requiredResourceAccess:
    - resourceAccess:
      - id: 37f7f235-527c-4136-accd-4a02d197296e
        type: Scope
      - id: 14dad69e-099b-42c9-810b-d002981feec1
        type: Scope
      - id: 64a6cdd6-aab1-4aaf-94b8-3cc8405e90d0
        type: Scope
      resourceAppId: 00000003-0000-0000-c000-000000000000
    serviceManagementReference: ""
    signInAudience: AzureADMyOrg
    singlePageApplication:
    - {}
    supportUrl: ""
    templateId: ""
    termsOfServiceUrl: ""
    web:
    - homepageUrl: ""
      implicitGrant:
      - accessTokenIssuanceEnabled: false
        idTokenIssuanceEnabled: false
      logoutUrl: ""
      redirectUris:
      - http://localhost:7007/api/auth/microsoft/handler/frame
      - https://oidc-guard.app.com/api/auth/microsoft/handler/frame
  conditions:
  - lastTransitionTime: 2024-07-18T16:04:33Z
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: 2024-07-18T16:04:31Z
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: 2024-07-18T16:04:32Z
    reason: Success
    status: "True"
    type: LastAsyncOperation