# Replace this with your XR!
apiVersion: azuread.company.com/v1alpha1
kind: xApplication
metadata:
  name: example-xr
spec:
  owners:
    - owner1@example.com
    - owner2@example.com
  requiredResourceAccess:
    - resourceAppId: "12345678-1234-1234-1234-1234567890ab"
      resourceAccess:
        - id: "11111111-1111-1111-1111-111111111111"
          type: "Scope"
        - id: "22222222-2222-2222-2222-222222222222"
          type: "Role"
  singlePageApplication:
    -  redirectUris:
        - "https://example.com/callback"
        - "https://example.com/redirect"
  web:
    - homepageUrl: "https://example.com"
      implicitGrant:
        - accessTokenIssuanceEnabled: true
          idTokenIssuanceEnabled: false
      logoutUrl: "https://example.com/logout"
      redirectUris:
        - "https://example.com/callback1"
        - "https://example.com/callback2"