apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: etls.data.company.com
spec:
  group: data.company.com
  scope: Namespaced
  names:
    kind: ETL
    plural: etls
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              owners:
                type: array
                items:
                 type: string
